var wordlist = [
    "Minecraft",
    "Chappal",
    "Dungeon",
    "Shit",
    "Poop",
    "Hamster",
    "T-shirt",
    "Basketball",
    "DJ Khaled",
    "Trump",
    "George W Bush",
    "Nasser",
    "ball",
    "Widget",
    "Chair",
    "Photo",
    "Hair",
    "Insect",
    "Water",
    "Helium",
    "Sodium Carbonate",
    "Pneumonoultramicroscopicsilicovolcanoconiosis",
    "Glitter",
    "Bunny",
    "Buns",
    "Cheeks",
    "Clouds",
    "Goat",
    "Ice",
    "Night vision",
    "Gordon Ramsay",
    "Governer",
    "Twat",
    "Beans",
    "hello pls help me i am under the water here too much raining uwuwuwuw",
    "Oreo",
    "Cups",
    "Bloke",
    "Bonkers",
    "Boondongle",
    "Doorknob",
    "Glass",
    "Jaw",
    "Eye",
    "Helicopter",
    "Porsche",
    "Lad",
    "Plastic",
    "Tupperware",
    "School",
    "College",
    "Hill",
    "Bracelet",
    "Shorts",
    "Bling-bling",
    "iPhone",
    "Samsung",
    "Water bottle",
    "Sleep",
    "iPad",
    "Android",
    "*insert pop noises*",
    "THAPANG",
    "Vineeth",
    "FIFA",
    "Justin Beiber",
    "Sudeep",
    "Nueoroglogist",
    "Physician",
    "Bob",
    "London",
    "Orange",
    "Business",
    "Suction cups",
    "Beanie",
    "Gulab jamun",
    "Pickle",
    "Cucumber",
    "Snake",
    "Whistle",
    "Florida",
    "Rice",
    "Mosquito",
    "whoever reads this is dumb",
    "Bones",
    "Engine",
    "Architect",
    "Strength",
    "Calcium",
    "Bat",
    "Baseball",
    "Musician",
    "Actor",
    "joe's right toenail",
    "joe's left toenail",
    "Hiccups",
    "Gum",
    "'MERICA!",
    "Sausage",
    "Monkey",
    "Horse",
    "Bell",
    "Belt",
    "Drums",
    "Plane",
    "V12 Engine",
    "RAM TRX",
    "Porsche 911 Turbo S",
    "Porscche 911 GT3 RS",
    "Rubberbands",
    "Luck"
];

